name: Deploy Astro Portfolio

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
        types: [closed]

jobs:
    deploy:
        # Only run on pushes to master or merged PRs from develop to master
        if: github.ref == 'refs/heads/master' && (github.event_name == 'push' || (github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master' && github.event.pull_request.head.ref == 'develop'))

        runs-on: ubuntu-latest

        steps:
            - name: Checkout source repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22.18.0'

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: '10.14.0'

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - name: Setup pnpm cache
              uses: actions/cache@v4
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build Astro site
              run: pnpm run build

            - name: Checkout target repository
              uses: actions/checkout@v4
              with:
                  repository: WanManolo/WanManolo.github.io
                  token: ${{ secrets.PUBLISH_TOKEN }}
                  path: target-repo

            - name: Clear target repository
              run: |
                  cd target-repo
                  find . -maxdepth 1 ! -name '.git' ! -name '.github' ! -name '.' -exec rm -rf {} +

            - name: Copy build files to target repository
              run: |
                  cp -r dist/* target-repo/

            - name: Configure Git
              run: |
                  cd target-repo
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"

            - name: Commit and push changes
              run: |
                  cd target-repo
                  git add .
                  if git diff --staged --quiet; then
                    echo "No changes to commit"
                  else
                    git commit -m "Deploy from astro-portfolio @ ${{ github.sha }}"
                    git push
                  fi
